# Generated by Django 4.2.11 on 2024-08-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_populate_observation_sat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='satellite',
        ),
        migrations.DeleteModel(
            name='Satellite',
        ),
    ]
