# Generated by Django 4.2.13 on 2025-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_alter_observation_sat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='transmitter_type',
            field=models.CharField(choices=[('Transmitter', 'Transmitter'), ('Transceiver', 'Transceiver'), ('Transponder', 'Transponder')], default='Transmitter', max_length=11),
        ),
    ]
