# Generated by Django 4.2.13 on 2025-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0126_add_validation_to_advanced_config_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='client_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
