# Generated by Django 4.2.13 on 2025-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0127_make_client_id_valid_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
