# Generated by Django 4.2.13 on 2025-02-19 13:17

from django.db import migrations, models
from django.db.models import F


def transform_station_status(apps, schema_editor):
    Station = apps.get_model('base', 'Station')
    Station.objects.update(is_available=~F('testing'))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0129_alter_station_client_id__field_to_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='stationstatuslog',
            name='base_statio_changed_71df65_idx',
        ),
        migrations.AddField(
            model_name='station',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(transform_station_status),
        migrations.AddField(
            model_name='stationstatuslog',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stationstatuslog',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stationstatuslog',
            name='testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['last_seen'], name='base_statio_last_se_d688ea_idx'),
        ),
        migrations.AddIndex(
            model_name='stationstatuslog',
            index=models.Index(
                fields=['station', '-changed'], name='base_statio_station_148b4a_idx'
            ),
        ),
    ]
