# Generated by Django 4.2.13 on 2024-11-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0131_transform_station_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='qthlocator',
        ),
    ]
