# Generated by Django 4.2.13 on 2025-08-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0132_remove_station_qthlocator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='vetted_status',
        ),
    ]
