# Generated by Django 4.2.13 on 2025-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0133_remove_observation_vetted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='transmitter_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
