# Generated by Django 4.2.28 on 2026-02-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0134_observation_transmitter_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="description",
            field=models.TextField(
                blank=True, help_text="Max 2000 characters", max_length=2000
            ),
        ),
    ]
