# Generated by Django 4.2.13 on 2026-01-26 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0134_observation_transmitter_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactVetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('waterfall', 'Waterfall')], default='waterfall', max_length=50)),
                ('vetted_status', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('unknown', 'Unknown')], max_length=20)),
                ('vetted_datetime', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_vettings', to='base.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_vettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artifact Vetting',
                'ordering': ['-vetted_datetime'],
                'permissions': (('can_vet_artifacts', 'Can vet observation artifacts'),),
                'indexes': [models.Index(fields=['observation', 'artifact_type'], name='base_artifa_observa_4f3131_idx'), models.Index(fields=['user'], name='base_artifa_user_id_3e9980_idx'), models.Index(fields=['-vetted_datetime'], name='base_artifa_vetted__e7b98c_idx')],
                'unique_together': {('user', 'observation', 'artifact_type')},
            },
        ),
    ]
