# Generated by Django 4.2.13 on 2026-01-27 14:09

from django.conf import settings
from django.db import migrations


def forwards_func(apps, schema_editor):
    """Migrate existing vetting data from Observation fields to ArtifactVetting model."""

    if getattr(settings, 'IGNORE_MIGRATION', False):
        return

    Observation = apps.get_model('base', 'Observation')
    ArtifactVetting = apps.get_model('base', 'ArtifactVetting')

    observations_with_vetting = Observation.objects.filter(waterfall_status_user__isnull=False)

    for obs in observations_with_vetting:

        if obs.waterfall_status is True:
            vetted_status = 'good'
        elif obs.waterfall_status is False:
            vetted_status = 'bad'
        else:
            vetted_status = 'unknown'

        # Check if vetting already exists (avoid duplicates)
        existing = ArtifactVetting.objects.filter(
            observation=obs, user=obs.waterfall_status_user, artifact_type='waterfall'
        ).exists()

        if existing:
            continue

        ArtifactVetting.objects.create(
            observation=obs,
            user=obs.waterfall_status_user,
            artifact_type='waterfall',
            vetted_status=vetted_status,
            vetted_datetime=obs.waterfall_status_datetime or obs.end
        )


def reverse_func(apps, schema_editor):
    """Reverse migration - delete migrated vetting data."""
    if getattr(settings, 'IGNORE_MIGRATION', False):
        return

    ArtifactVetting = apps.get_model('base', 'ArtifactVetting')
    ArtifactVetting.objects.filter(artifact_type='waterfall').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0135_artifactvetting'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
