# Generated by Django 4.2.13 on 2025-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0137_migrate_vetting_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='horizon_hard_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='min_culmination',
            field=models.PositiveIntegerField(default=10, help_text='In degrees above 0'),
        ),
        migrations.AddField(
            model_name='station',
            name='min_culmination_hard_limit',
            field=models.BooleanField(default=False),
        ),
    ]
