# Generated by Django 4.2.13 on 2026-06-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0138_station_horizon_hard_limit_station_min_culmination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationUnavailabilityPeriod',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'station',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='unavailable_periods',
                        to='base.station'
                    )
                ),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.AddIndex(
            model_name='stationunavailabilityperiod',
            index=models.Index(
                fields=['station', 'start', 'end'], name='base_unavail_period_idx'
            ),
        ),
    ]
